### ISSUE TITLE
deploy.sh not include ??

### ISSUE THREAD

**Issue by cuong95nddev** [syscl/Inspiron15-5547#5]
where can I get this file.
Thank for the good job.

**Comment by syscl** [comment]
HI, deploy not include in this project. This project use dynamic ACPI patching to avoid static ACPI cause failure patching.

Thank you,
syscl

**Comment by cuong95nddev** [comment]
I use your project to make clover boot but get crashes in boot screen "apple".
Here is my project i make myself: https://github.com/anhbinhvodanh/Dell-5547-Hackintosh

**Comment by khanghh** [comment]
how can i patch my ACPI tables ?

**Comment by cuong95nddev** [comment]
@hoanghongkhang mình đã patch và dùng ổn định rồi nè bạn có thể dùng project này của mình
https://github.com/anhbinhvodanh/Dell-5547-Hackintosh

**Comment by khanghh** [comment]
HDMI ok không bạn ? Mình đang chạy hack của bạn nè. geekbenh thấp hơn windows xíu nhưng mọi thứ chạy ngon lắm :))

**Comment by syscl** [comment]
@hoanghongkhang VoodooHDA gives the HDMI support.

On AppleALC, still need frame buffer edit.

syscl

**Comment by khanghh** [comment]
@syscl I can not get your hack to work. It seem to be missing patched DSDT/SSDT in Inspiron15-5547/CLOVER/ACPI/patched/

**Comment by cuong95nddev** [comment]
@hoanghongkhang mình chưa test HDMI bạn test thử rồi nhắn mình nhé

**Comment by syscl** [comment]
This is my friend's laptop and I can use this to boot macOS 10.12.6+ without any problem.

No need to patch DSDT because I use hot patch on his laptop.

syscl

**Comment by khanghh** [comment]
@anhbinhvodanh có fb ko mình hỏi xíu

**Comment by cuong95nddev** [comment]
@hoanghongkhang /cuong95nd

**Comment by cuong95nddev** [comment]
@hoanghongkhang HDMI làm việc tốt nhé bạn, mới test sáng nay trong buổi thuyết trình.

**Comment by khanghh** [comment]
@anhbinhvodanh  check ib fb anh oi

**Comment by cuong95nddev** [comment]
@hoanghongkhang Gửi lại tin nhắn đi

**Comment by khanghh** [comment]
@anhbinhvodanh  roi anh
